old/S9-PhoenixModel/discuss/lib/discuss_web/router.ex
defmodule DiscussWeb.Router do
  use DiscussWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:put_root_layout, html: {DiscussWeb.Layouts, :root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", DiscussWeb do
    pipe_through(:browser)

    get("/", PageController, :home)
    get("/topics/new", TopicController, :new)
  end

  # Other scopes may use custom stacks.
  # scope "/api", DiscussWeb do
  #   pipe_through :api
  # end

  # Enable LiveDashboard and Swoosh mailbox preview in development
  if Application.compile_env(:discuss, :dev_routes) do
    # If you want to use the LiveDashboard in production, you should put
    # it behind authentication and allow only admins to access it.
    # If your application does not have an admins-only section yet,
    # you can use Plug.BasicAuth to set up some basic authentication
    # as long as you are also using SSL (which you should anyway).
    import Phoenix.LiveDashboard.Router

    scope "/dev" do
      pipe_through(:browser)

      live_dashboard("/dashboard", metrics: DiscussWeb.Telemetry)
      forward("/mailbox", Plug.Swoosh.MailboxPreview)
    end
  end
end

old/S9-PhoenixModel/discuss/lib/discuss/application.ex
defmodule Discuss.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  @impl true
  def start(_type, _args) do
    children = [
      DiscussWeb.Telemetry,
      Discuss.Repo,
      {DNSCluster, query: Application.get_env(:discuss, :dns_cluster_query) || :ignore},
      {Phoenix.PubSub, name: Discuss.PubSub},
      # Start the Finch HTTP client for sending emails
      {Finch, name: Discuss.Finch},
      # Start a worker by calling: Discuss.Worker.start_link(arg)
      # {Discuss.Worker, arg},
      # Start to serve requests, typically the last entry
      DiscussWeb.Endpoint
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Discuss.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  @impl true
  def config_change(changed, _new, removed) do
    DiscussWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

old/S9-PhoenixModel/discuss/lib/discuss/mailer.ex
defmodule Discuss.Mailer do
  use Swoosh.Mailer, otp_app: :discuss
end

old/S9-PhoenixModel/discuss/lib/discuss/repo.ex
defmodule Discuss.Repo do
  use Ecto.Repo,
    otp_app: :discuss,
    adapter: Ecto.Adapters.Postgres
end

old/S9-PhoenixModel/discuss/lib/discuss_web/controllers/error_html.ex
defmodule DiscussWeb.ErrorHTML do
  use DiscussWeb, :html

  # If you want to customize your error pages,
  # uncomment the embed_templates/1 call below
  # and add pages to the error directory:
  #
  #   * lib/discuss_web/controllers/error_html/404.html.heex
  #   * lib/discuss_web/controllers/error_html/500.html.heex
  #
  # embed_templates "error_html/*"

  # The default is to render a plain text page based on
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def render(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

old/S9-PhoenixModel/discuss/lib/discuss_web/controllers/page_controller.ex
defmodule DiscussWeb.PageController do
  use DiscussWeb, :controller

  def home(conn, _params) do
    # The home page is often custom made,
    # so skip the default app layout.
    render(conn, :home, layout: false)
  end
end

old/S9-PhoenixModel/discuss/lib/discuss_web/controllers/page_html.ex
defmodule DiscussWeb.PageHTML do
  use DiscussWeb, :html

  embed_templates "page_html/*"
end

old/S9-PhoenixModel/discuss/lib/discuss_web/controllers/topic_controller.ex
defmodule Discuss.TopicController do
  use DiscussWeb, :controller

  alias Discuss.Topic

  def new(conn, params) do
    changeset = Topic.changeset(%Topic{}, %{})
    render(conn, "new.html", changeset: changeset)
  end
end

old/S9-PhoenixModel/discuss/lib/discuss_web/views/topic_view.ex
defmodule Discuss.TopicView do
  use DiscussWeb, :view
end

old/S9-PhoenixModel/discuss/lib/discuss_web/components/layouts/app.html.heex
<header class="px-4 sm:px-6 lg:px-8">
  <div class="flex items-center justify-between border-b border-zinc-100 py-3 text-sm">
    <div class="flex items-center gap-4">
      <a href="/">
        <img src={~p"/images/logo.svg"} width="36" />
      </a>
      <p class="bg-brand/5 text-brand rounded-full px-2 font-medium leading-6">
        v<%= Application.spec(:phoenix, :vsn) %>
      </p>
    </div>
    <div class="flex items-center gap-4 font-semibold leading-6 text-zinc-900">
      <a href="https://twitter.com/elixirphoenix" class="hover:text-zinc-700">
        @elixirphoenix
      </a>
      <a href="https://github.com/phoenixframework/phoenix" class="hover:text-zinc-700">
        GitHub
      </a>
      <a
        href="https://hexdocs.pm/phoenix/overview.html"
        class="rounded-lg bg-zinc-100 px-2 py-1 hover:bg-zinc-200/80"
      >
        Get Started <span aria-hidden="true">&rarr;</span>
      </a>
    </div>
  </div>
</header>
<main class="px-4 py-20 sm:px-6 lg:px-8">
  <div class="mx-auto max-w-2xl">
    <.flash_group flash={@flash} />
    <%= @inner_content %>
  </div>
</main>

old/S9-PhoenixModel/discuss/lib/discuss_web/components/layouts/root.html.heex
<!DOCTYPE html>
<html lang="en" class="[scrollbar-gutter:stable]">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="csrf-token" content={get_csrf_token()} />
    <.live_title suffix=" · Phoenix Framework">
      <%= assigns[:page_title] || "Discuss" %>
    </.live_title>
    <link phx-track-static rel="stylesheet" href={~p"/assets/app.css"} />
    <script defer phx-track-static type="text/javascript" src={~p"/assets/app.js"}>
    </script>
  </head>
  <body class="bg-white antialiased">
    <nav class="bg-brand">
      <div class="mx-auto w-full sm:max-w-xl lg:max-w-[1500px] xl:max-w- md:px-0 lg:px-8 xl:px-28">
        <div class="relative flex h-16 items-center justify-between">
          <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
            <!-- Mobile menu button-->
            <button type="button" class="relative inline-flex items-center justify-center rounded-md p-2 mx-2 text-white hover:bg-white hover:text-brand focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
              <span class="absolute -inset-0.5"></span>
              <span class="sr-only">Open main menu</span>
              <!--
                Icon when menu is closed.

                Menu open: "hidden", Menu closed: "block"
              -->
              <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
              </svg>
              <!--
                Icon when menu is open.

                Menu open: "block", Menu closed: "hidden"
              -->
              <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
          <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
            <div class="hidden sm:block">
              <div class="flex space-x-4">
                <!-- Current: "bg-white text-brand", Default: "text-gray-300 hover:bg-gray-700 hover:text-brand" -->
                <a href="#" class="bg-white text-brand rounded-md px-3 py-2 text-sm font-medium" aria-current="page">Discussion</a>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Mobile menu, show/hide based on menu state. -->
      <div class="sm:hidden" id="mobile-menu">
        <div class="space-y-1 px-2 pb-3 pt-2">
          <!-- Current: "bg-white text-brand", Default: "text-gray-300 hover:bg-gray-700 hover:text-brand" -->
          <a href="#" class="bg-white text-brand block rounded-md px-3 py-2 text-base font-medium" aria-current="page">Discussion</a>
        </div>
      </div>
    </nav>
    <%= @inner_content %>
  </body>
</html>

old/S9-PhoenixModel/discuss/lib/discuss_web/controllers/topics/new.html.heex
<%= form_for @changeset, topic_path(@conn, :create), fn f -> %>
    <div class="form-group">
        <% text_input f, :title, placeholder: "Title", class: "form-control" %>
        <%= error_tag f, :title %>
    </div>

    <%= submit "Save Topic", class: "btn btn-primary" %>
<% end %>